# Generated by Django 2.1.3 on 2018-12-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='priority',
            field=models.CharField(default='high', max_length=4),
        ),
    ]
